name: Wolf Bot Clean Run

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run bot
        env:
          U_MAIL_1: ${{ secrets.U_MAIL_1 }}
          U_PASS_1: ${{ secrets.U_PASS_1 }}
        run: node app.js
